import express from'express';
// import { Router } from 'express';
import {signupController} from "../Controller/signupController.js";
import {loginController} from "../Controller/loginController.js";
import { addTaskController } from '../Controller/addTaskController.js';
import { loadTaskController } from '../Controller/loadTaskController.js';
import { editController } from '../Controller/editController.js';
const router=express.Router();
console.log("reached to routes");
router.post("/signup",signupController);
router.post("/login",loginController);
router.post("/addtask",addTaskController);
router.post("/loadtask",loadTaskController);
router.post("/edit",editController);
export default router;